### ISSUE TITLE
QQ\微信登录 提示json字符串

### ISSUE THREAD

**Issue by zjafei** [GrizzlyTechnology/grizzlyPersonalApp#148]
QQ\微信登录 提示json字符串
![tim 20181115163912](https://user-images.githubusercontent.com/8189405/48540462-22022e80-e8f5-11e8-8d63-dbeb5ec2516c.png)

**Comment by zjafei** [comment]
@dingyijun  你看看

**Comment by dingyijun** [comment]
OK

**Comment by dingyijun** [comment]
已经解决
