### ISSUE TITLE
修改密码页面，新密码与旧密码一致时报错

### ISSUE THREAD

**Issue by lingwu** [GrizzlyTechnology/grizzlyPersonalApp#164]
修改密码页面，新密码与旧密码一直时报错
![6](https://user-images.githubusercontent.com/4616774/48592900-853ba180-e985-11e8-853d-96c6f744d4c6.png)

**Comment by lingwu** [comment]
已修改验证
![13](https://user-images.githubusercontent.com/4616774/48600282-37836100-e9a6-11e8-8700-1fe261b329a0.png)

**Comment by zjafei** [comment]
666 我都忘了
