### ISSUE TITLE
上传头像时，明明已经登录了，但是提示未登录，上传也不成功

### ISSUE THREAD

**Issue by lingwu** [GrizzlyTechnology/grizzlyPersonalApp#166]
上传头像时，明明已经登录了，但是提示未登录，上传也不成功
![8](https://user-images.githubusercontent.com/4616774/48593403-ac936e00-e987-11e8-9d6f-2a8c19a25b4b.png)

**Comment by lingwu** [comment]
所有的上传图片都会提示未登录

**Comment by dingyijun** [comment]
已经解决是把token写死了
