### ISSUE TITLE
我的简历 荣誉展示，显示问题

### ISSUE THREAD

**Issue by lingwu** [GrizzlyTechnology/grizzlyPersonalApp#168]
我的简历 荣誉展示，显示问题
![10](https://user-images.githubusercontent.com/4616774/48593571-4a873880-e988-11e8-91ea-ff9363be714a.png)

**Comment by zjafei** [comment]
产品的需求就是这个的把 @nangangmutong

**Comment by lingwu** [comment]
已修改
![14](https://user-images.githubusercontent.com/4616774/48600683-e5dbd600-e9a7-11e8-838a-64a14446c29d.png)

**Comment by dingyijun** [comment]
荣誉现在添加不了，空白页

**Comment by lingwu** [comment]
> 荣誉现在添加不了，空白页

tools写成了tool
![qq 20181118120047](https://user-images.githubusercontent.com/4616774/48668708-62e58780-eb2f-11e8-8627-27f160cabf25.png)

**Comment by zjafei** [comment]
@lingwu  改成这样了 
![tim 20181121204810](https://user-images.githubusercontent.com/8189405/48842450-48313e00-edcf-11e8-85bf-b4a4ff0f418f.png)
