### ISSUE TITLE
刚开始新建的时候不修改时间时，不报错，修改一下时间，在修改成一样的时间时报错

### ISSUE THREAD

**Issue by lingwu** [GrizzlyTechnology/grizzlyPersonalApp#169]
刚开始新建的时候不修改时间时，不报错，修改一下时间，在修改成一样的时间时报错
![11](https://user-images.githubusercontent.com/4616774/48593633-9e921d00-e988-11e8-90f9-a15f78ce8daf.png)

**Comment by zjafei** [comment]
这个时间相同可以么 @nangangmutong

**Comment by zjafei** [comment]
@lingwu 修改开始时间与结束时间重复的问题 开始时间默认为当前月的前一个月
[https://github.com/GrizzlyTechnology/grizzlyPersonalApp/pull/255](url)

**Comment by lingwu** [comment]
已测试 @nangangmutong
