### ISSUE TITLE
点击【提交】后，提交不成功。红框处增加空白位置

### ISSUE THREAD

**Issue by nangangmutong** [GrizzlyTechnology/grizzlyPersonalApp#227]
![default](https://user-images.githubusercontent.com/31693972/48755540-990e3d00-ecd0-11e8-8956-a07ba1c5672a.png)

**Comment by lingwu** [comment]
哪个浏览器？

**Comment by lingwu** [comment]
![image](https://user-images.githubusercontent.com/4616774/48812021-59486380-ed6b-11e8-91e7-562b708974c0.png)

**Comment by lingwu** [comment]
![image](https://user-images.githubusercontent.com/4616774/48812477-8138c680-ed6d-11e8-820d-ffd43e7ab55b.png)
已修改
