### ISSUE TITLE
首页名企推荐图片大小不一

### ISSUE THREAD

**Issue by lingwu** [GrizzlyTechnology/grizzlyPersonalApp#230]
首页名企推荐图片大小不一
![15](https://user-images.githubusercontent.com/4616774/48813848-80a32e80-ed73-11e8-86ec-4e4e2882ad45.png)

**Comment by lingwu** [comment]
已修改
![16](https://user-images.githubusercontent.com/4616774/48814376-7da93d80-ed75-11e8-91c2-39e3d7908c5b.png)

**Comment by zjafei** [comment]
@lingwu 没企业头型的怎么解决

**Comment by lingwu** [comment]
> @lingwu 没企业头型的怎么解决

企业logo是必须上传的
