### ISSUE TITLE
统一全平台logo与产品名称

### ISSUE THREAD

**Issue by nangangmutong** [GrizzlyTechnology/grizzlyPersonalApp#232]
统一改为“ MR GRIZZLY 灰熊先生”
![image](https://user-images.githubusercontent.com/31693972/48815132-49834c00-ed78-11e8-9786-a71c6de469a6.png)
![image](https://user-images.githubusercontent.com/31693972/48815140-52741d80-ed78-11e8-9dfb-644d94bc8ae6.png)
![image](https://user-images.githubusercontent.com/31693972/48815147-5b64ef00-ed78-11e8-822d-a2ee52d8e0be.png)

**Comment by lingwu** [comment]
已改
![image](https://user-images.githubusercontent.com/4616774/48827536-78191b00-eda8-11e8-9f68-430621342127.png)
![image](https://user-images.githubusercontent.com/4616774/48827550-7ea79280-eda8-11e8-913f-82be33ac1359.png)
![image](https://user-images.githubusercontent.com/4616774/48827557-82d3b000-eda8-11e8-90e4-1dadfc84e650.png)
 @nangangmutong
