### ISSUE TITLE
在安卓版APP上（华为）创建简历时报错

### ISSUE THREAD

**Issue by syqjulia** [GrizzlyTechnology/grizzlyPersonalApp#234]
![screenshot_20181121_102403_com y84749353 psu](https://user-images.githubusercontent.com/45085635/48815381-53597f00-ed79-11e8-970e-73896dda33a4.jpg)

**Comment by zjafei** [comment]
@syqjulia  已修复
[https://github.com/GrizzlyTechnology/grizzlyPersonalApp/pull/256](url)
