### ISSUE TITLE
安卓版（华为）APP教育经历可填同年同月

### ISSUE THREAD

**Issue by syqjulia** [GrizzlyTechnology/grizzlyPersonalApp#235]
![screenshot_20181121_102945_com y84749353 psu](https://user-images.githubusercontent.com/45085635/48815423-77b55b80-ed79-11e8-959e-621188d6785f.jpg)
![screenshot_20181121_102242_com y84749353 psu](https://user-images.githubusercontent.com/45085635/48815426-7ab04c00-ed79-11e8-8543-cda5be629423.jpg)

**Comment by lingwu** [comment]
这个问题已提过 详见 #170

**Comment by zjafei** [comment]
@syqjulia  嗯这个一类的问题我改了4个issue kpi 满满的

**Comment by zjafei** [comment]
@syqjulia 修复了

**Comment by lingwu** [comment]
已测试 @syqjulia
