### ISSUE TITLE
安卓版APP（华为），刚在平台上注册的公司显示在名企推荐栏

### ISSUE THREAD

**Issue by syqjulia** [GrizzlyTechnology/grizzlyPersonalApp#236]
![screenshot_20181121_102030_com y84749353 psu](https://user-images.githubusercontent.com/45085635/48815538-c06d1480-ed79-11e8-9aa7-1935e5ad848d.jpg)

**Comment by lingwu** [comment]
已修改
![17](https://user-images.githubusercontent.com/4616774/48821456-5f9f0580-ed94-11e8-8e5f-59609772188f.png)
