### ISSUE TITLE
荣耀手机注册账号之后屏幕变白

### ISSUE THREAD

**Issue by syqjulia** [GrizzlyTechnology/grizzlyPersonalApp#242]
荣耀手机注册账号后屏幕变白
华为手机登陆APP后点击返回键退出时，也显示空白页
![1542777730230](https://user-images.githubusercontent.com/45085635/48820704-1dc09000-ed91-11e8-8d9f-9abd7a75672d.jpg)
![img_20181121_132535](https://user-images.githubusercontent.com/45085635/48820706-1f8a5380-ed91-11e8-99ef-70a917fd0c8d.jpg)
![image](https://user-images.githubusercontent.com/45085635/48888212-e1faf880-ee6c-11e8-824d-8b7d6db2c77d.png)

**Comment by lingwu** [comment]
已修改 @syqjulia
