### ISSUE TITLE
安卓和苹果端选择忘记密码时出现弹窗

### ISSUE THREAD

**Issue by syqjulia** [GrizzlyTechnology/grizzlyPersonalApp#246]
![img_0483](https://user-images.githubusercontent.com/45085635/48821781-99244080-ed95-11e8-9fa6-61360c2bee06.PNG)
![screenshot_20181121_135531_com y84749353 psu](https://user-images.githubusercontent.com/45085635/48821785-9a556d80-ed95-11e8-86ef-fdbc4d6ac2b7.jpg)

**Comment by zjafei** [comment]
@syqjulia  忘记密码功在做了 release/0.2后面的版本上
