### ISSUE TITLE
APP端不同账号绑定同一邮箱显示创建失败（安卓和苹果）

### ISSUE THREAD

**Issue by syqjulia** [GrizzlyTechnology/grizzlyPersonalApp#270]
![image](https://user-images.githubusercontent.com/45085635/48927001-92b8d480-ef0d-11e8-8a5d-9b782418c3b0.png)
不同账号绑定同一邮箱，将弹窗改成“该邮箱已被绑定”
其他情况未绑定成功，显示“绑定失败，请稍后重试！”

**Comment by zjafei** [comment]
@syqjulia 已经添加修改了 直接报后端输出的message
