### ISSUE TITLE
APP/提交学籍后报错，已经加入学籍仍能填写信息（安卓）

### ISSUE THREAD

**Issue by syqjulia** [GrizzlyTechnology/grizzlyPersonalApp#325]
提交学籍后报错
![image](https://user-images.githubusercontent.com/45085635/49273205-31fe3e80-f4af-11e8-8090-889e38b99bd9.png)
![image](https://user-images.githubusercontent.com/45085635/49273228-44787800-f4af-11e8-86e8-5875c2938ef3.png)

**Comment by lingwu** [comment]
哪个手机？ @syqjulia

**Comment by syqjulia** [comment]
华为mate20@lingwu

**Comment by zjafei** [comment]
> 华为mate20 @lingwu
要有空格 要不然不起作用的 @syqjulia
